<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * All email notifications generated by the per-seat billing system.
 * Subscription-expiry emails remain in GLD_Cron.
 */
class GLD_Notifications {

	// ── Seat charge receipt ───────────────────────────────────────────────────

	/**
	 * @param array $charge {
	 *   group_id, user_name, user_email, amount, currency,
	 *   period_start, period_end, flw_ref
	 * }
	 */
	public static function charge_receipt( int $leader_id, array $charge ): void {
		$leader = get_userdata( $leader_id );
		if ( ! $leader ) return;

		$site      = get_bloginfo( 'name' );
		$group     = esc_html( get_the_title( $charge['group_id'] ) );
		$name      = esc_html( $charge['user_name'] );
		$email     = esc_html( $charge['user_email'] );
		$amount    = number_format( (float) $charge['amount'], 2 );
		$currency  = esc_html( $charge['currency'] );
		$from      = esc_html( date( 'F j, Y', strtotime( $charge['period_start'] ) ) );
		$to        = esc_html( date( 'F j, Y', strtotime( $charge['period_end'] ) ) );
		$ref       = esc_html( $charge['flw_ref'] ?? '' );
		$dash_url  = GLD_Auth::dashboard_url();

		$body = self::email_wrap( "
			<p>Hi {$leader->display_name},</p>
			<p>A seat has been added to your group <strong>{$group}</strong> and your card has been charged.</p>
			<table style='width:100%;border-collapse:collapse;font-size:13px;margin:20px 0;'>
				<tr style='background:#f9fafb;'><td style='padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;width:40%'>Learner</td><td style='padding:8px 12px;border:1px solid #e5e7eb;'>{$name}<br><span style='color:#6b7280;'>{$email}</span></td></tr>
				<tr><td style='padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;'>Amount charged</td><td style='padding:8px 12px;border:1px solid #e5e7eb;'><strong>{$currency} {$amount}</strong></td></tr>
				<tr style='background:#f9fafb;'><td style='padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;'>Access period</td><td style='padding:8px 12px;border:1px solid #e5e7eb;'>{$from} – {$to}</td></tr>
				" . ( $ref ? "<tr><td style='padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;'>Reference</td><td style='padding:8px 12px;border:1px solid #e5e7eb;color:#6b7280;'>{$ref}</td></tr>" : '' ) . "
			</table>
			<p><a href='" . esc_url( $dash_url ) . "' style='color:#4f46e5;font-weight:600;'>View your billing history →</a></p>
		", $site );

		wp_mail(
			$leader->user_email,
			"[{$site}] Seat charge receipt — {$name}",
			$body,
			self::html_headers()
		);
	}

	// ── Charge failure ────────────────────────────────────────────────────────

	/**
	 * @param array $data {
	 *   group_id, user_name, user_email, amount, currency, error
	 * }
	 */
	public static function charge_failure( int $leader_id, array $data ): void {
		$leader = get_userdata( $leader_id );
		if ( ! $leader ) return;

		$site     = get_bloginfo( 'name' );
		$group    = esc_html( get_the_title( $data['group_id'] ) );
		$name     = esc_html( $data['user_name'] );
		$amount   = number_format( (float) $data['amount'], 2 );
		$currency = esc_html( $data['currency'] );
		$error    = esc_html( $data['error'] ?? 'Unknown error.' );
		$dash_url = GLD_Auth::dashboard_url();

		$body = self::email_wrap( "
			<p>Hi {$leader->display_name},</p>
			<p>A seat charge for your group <strong>{$group}</strong> failed. The learner <strong>{$name}</strong> has <strong>not</strong> been added to the group.</p>
			<table style='width:100%;border-collapse:collapse;font-size:13px;margin:20px 0;'>
				<tr style='background:#f9fafb;'><td style='padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;width:40%'>Learner</td><td style='padding:8px 12px;border:1px solid #e5e7eb;'>{$name}</td></tr>
				<tr><td style='padding:8px 12px;border:1px solid #e5e7eb;font-weight:600;'>Amount</td><td style='padding:8px 12px;border:1px solid #e5e7eb;'>{$currency} {$amount}</td></tr>
				<tr style='background:#fef2f2;'><td style='padding:8px 12px;border:1px solid #fca5a5;font-weight:600;color:#991b1b;'>Failure reason</td><td style='padding:8px 12px;border:1px solid #fca5a5;color:#991b1b;'>{$error}</td></tr>
			</table>
			<p>We will automatically retry this charge over the next 3 days. If all retries fail, we will contact you again.</p>
			<p>To resolve this now, please check your saved card in the Billing section of your dashboard.</p>
			<p style='margin-top:20px;'>
				<a href='" . esc_url( $dash_url ) . "' style='background:#4f46e5;color:#fff;padding:10px 20px;border-radius:7px;text-decoration:none;font-weight:600;display:inline-block;'>Go to Dashboard</a>
			</p>
		", $site );

		wp_mail(
			$leader->user_email,
			"[{$site}] Action needed — seat charge failed for {$name}",
			$body,
			self::html_headers()
		);
	}

	/**
	 * Sent after all automatic retries are exhausted.
	 */
	public static function charge_failure_final( int $leader_id, array $data ): void {
		$leader = get_userdata( $leader_id );
		if ( ! $leader ) return;

		$site     = get_bloginfo( 'name' );
		$group    = esc_html( get_the_title( $data['group_id'] ) );
		$name     = esc_html( $data['user_name'] );
		$amount   = number_format( (float) $data['amount'], 2 );
		$currency = esc_html( $data['currency'] );
		$dash_url = GLD_Auth::dashboard_url();

		$body = self::email_wrap( "
			<p>Hi {$leader->display_name},</p>
			<p>We were unable to add <strong>{$name}</strong> to your group <strong>{$group}</strong> after multiple payment attempts. No further retries will be made.</p>
			<p><strong>What to do:</strong></p>
			<ol>
				<li>Go to the <strong>Billing</strong> section of your dashboard and update your payment card.</li>
				<li>Then add <strong>{$name}</strong> again from the <strong>Users</strong> tab.</li>
			</ol>
			<p style='margin-top:20px;'>
				<a href='" . esc_url( $dash_url ) . "' style='background:#dc2626;color:#fff;padding:10px 20px;border-radius:7px;text-decoration:none;font-weight:600;display:inline-block;'>Update Card &amp; Retry</a>
			</p>
			<p style='color:#6b7280;font-size:12px;'>Amount: {$currency} {$amount}</p>
		", $site );

		wp_mail(
			$leader->user_email,
			"[{$site}] Seat charge permanently failed — please update your card",
			$body,
			self::html_headers()
		);
	}

	// ── Bulk import summary ───────────────────────────────────────────────────

	/**
	 * Sent after a CSV/XLSX import completes.
	 */
	public static function import_summary( int $leader_id, int $group_id, array $totals, array $succeeded, array $skipped, array $failed ): void {
		$leader = get_userdata( $leader_id );
		if ( ! $leader ) return;

		$site  = get_bloginfo( 'name' );
		$group = esc_html( get_the_title( $group_id ) );
		$total = $totals['succeeded'] + $totals['skipped'] + $totals['failed'];

		// Build succeeded rows.
		$added_rows = '';
		foreach ( $succeeded as $r ) {
			$badge       = $r['new_account'] ? '<span style="background:#dbeafe;color:#1e40af;border-radius:4px;padding:1px 6px;font-size:11px;font-weight:600;margin-left:6px;">New</span>' : '';
			$added_rows .= "<tr><td style='padding:6px 10px;border:1px solid #e5e7eb;'>" . esc_html( $r['name'] ) . "{$badge}</td><td style='padding:6px 10px;border:1px solid #e5e7eb;color:#6b7280;'>" . esc_html( $r['email'] ) . "</td></tr>";
		}

		// Build failed rows.
		$failed_rows = '';
		foreach ( $failed as $r ) {
			$failed_rows .= "<tr><td style='padding:6px 10px;border:1px solid #fca5a5;color:#991b1b;'>" . esc_html( $r['email'] ) . "</td><td style='padding:6px 10px;border:1px solid #fca5a5;color:#991b1b;'>" . esc_html( $r['reason'] ) . "</td></tr>";
		}

		$added_section  = $added_rows
			? "<h3 style='color:#065f46;margin:20px 0 8px;'>&#10003; Added ({$totals['succeeded']})</h3><table style='width:100%;border-collapse:collapse;font-size:12px;'><tr style='background:#f9fafb;'><th style='padding:6px 10px;border:1px solid #e5e7eb;text-align:left;'>Name</th><th style='padding:6px 10px;border:1px solid #e5e7eb;text-align:left;'>Email</th></tr>{$added_rows}</table>"
			: '';

		$failed_section = $failed_rows
			? "<h3 style='color:#991b1b;margin:20px 0 8px;'>&#10007; Failed ({$totals['failed']})</h3><table style='width:100%;border-collapse:collapse;font-size:12px;'><tr style='background:#fef2f2;'><th style='padding:6px 10px;border:1px solid #fca5a5;text-align:left;color:#991b1b;'>Email</th><th style='padding:6px 10px;border:1px solid #fca5a5;text-align:left;color:#991b1b;'>Reason</th></tr>{$failed_rows}</table><p style='font-size:12px;color:#6b7280;'>Failed charges will be retried automatically over the next 3 days.</p>"
			: '';

		$skipped_note = $totals['skipped']
			? "<p style='color:#6b7280;font-size:13px;'>{$totals['skipped']} row(s) were skipped — those learners are already in the group.</p>"
			: '';

		$dash_url = GLD_Auth::dashboard_url();

		$body = self::email_wrap( "
			<p>Hi {$leader->display_name},</p>
			<p>Your bulk import into <strong>{$group}</strong> is complete.</p>
			<table style='width:100%;border-collapse:collapse;font-size:13px;margin:16px 0 4px;'>
				<tr>
					<td style='padding:10px 14px;background:#d1fae5;border-radius:6px;text-align:center;width:30%;'>
						<div style='font-size:22px;font-weight:700;color:#065f46;'>{$totals['succeeded']}</div>
						<div style='font-size:12px;color:#065f46;'>Added</div>
					</td>
					<td style='width:5%;'></td>
					<td style='padding:10px 14px;background:#f3f4f6;border-radius:6px;text-align:center;width:30%;'>
						<div style='font-size:22px;font-weight:700;color:#374151;'>{$totals['skipped']}</div>
						<div style='font-size:12px;color:#6b7280;'>Skipped</div>
					</td>
					<td style='width:5%;'></td>
					<td style='padding:10px 14px;background:#fee2e2;border-radius:6px;text-align:center;width:30%;'>
						<div style='font-size:22px;font-weight:700;color:#991b1b;'>{$totals['failed']}</div>
						<div style='font-size:12px;color:#991b1b;'>Failed</div>
					</td>
				</tr>
			</table>
			{$added_section}
			{$skipped_note}
			{$failed_section}
			<p style='margin-top:24px;'><a href='" . esc_url( $dash_url ) . "' style='color:#4f46e5;font-weight:600;'>View group in dashboard →</a></p>
		", $site );

		wp_mail(
			$leader->user_email,
			"[{$site}] Bulk import complete — {$totals['succeeded']} of {$total} added to {$group}",
			$body,
			self::html_headers()
		);
	}

	// ── Helpers ───────────────────────────────────────────────────────────────

	private static function email_wrap( string $content, string $site_name ): string {
		$year = date( 'Y' );
		$name = esc_html( $site_name );
		return '<!DOCTYPE html><html><body style="margin:0;padding:0;background:#f5f6fa;font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 20px;"><tr><td align="center">
<table width="580" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:10px;box-shadow:0 1px 3px rgba(0,0,0,.1);overflow:hidden;">
  <tr><td style="background:#4f46e5;padding:22px 32px;"><span style="color:#fff;font-size:17px;font-weight:700;">' . $name . '</span></td></tr>
  <tr><td style="padding:28px 32px;font-size:14px;color:#111827;line-height:1.7;">' . $content . '</td></tr>
  <tr><td style="padding:14px 32px;border-top:1px solid #e5e7eb;font-size:11px;color:#6b7280;">&copy; ' . $year . ' ' . $name . '. Automated message — do not reply.</td></tr>
</table>
</td></tr></table></body></html>';
	}

	private static function html_headers(): array {
		return array( 'Content-Type: text/html; charset=UTF-8' );
	}
}
